- name: install git
  apt:
    name: git
    update_cache: yes
    state: latest

- name: Копируем репозиторий moodle 4.5.2
  git:
    repo: https://github.com/moodle/moodle.git
    dest: /var/www/html/moodle
    version: MOODLE_405_STABLE
    clone: yes
