- name: install git
  apt:
    name: git
    update_cache: yes
    state: latest

- name: Копируем репозиторий moodle 4.5.2
  git:
    repo: https://github.com/moodle/moodle.git
    dest: /var/www/html/moodle
    version: MOODLE_405_STABLE
    clone: yes

- name: "Создать папку /var/www/html/moodledata"
  ansible.builtin.file:
    path: /var/www/html/moodledata
    state: directory
    mode: '0777'  # права доступа (опционально)
    owner: www-data  # владелец (обычно веб-сервер, опционально)
    group: www-data  # группа (опционально)
