- name: edit php.ini file
  ansible.builtin.lineinfile:
    path: /etc/php/8.1/apache2/php.ini 
    line: "max_input_vars=5000"

- name: edit files rules 
  ansible.builtin.file:
    path: /var/www/
    mode: "0777"
    owner: www-data
    group: www-data

- name: edit files rules
  ansible.builtin.file:
    path: /var/www/html/moodle
    mode: "0777"
    owner: www-data
    group: www-data
  notify: restart apache

- name: Add Moodle cron job for www-data user
  ansible.builtin.cron:
    name: "Moodle cron"
    user: "www-data"
    job: "/usr/bin/php /var/www/html/moodle/admin/cli/cron.php >/dev/null"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
