- name: install mariadb
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started

- name: set mysql root password
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    host_all: yes

- name: Create Moodle database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"