- name: Install php packages
  apt:
    name:
      - php8.2
      - php8.2-mysql
      - php8.2-curl
      - php8.2-gd
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-zip
      - php8.2-intl
      - php8.2-ldap
      - libapache2-mod-php8.2
      - php8.2-fpm
      - php8.2-intl
      - php8.2-soap
    state: present
  ignore_errors: True

- name: Запустить сервис Apache2
  service:
    name: apache2
    state: started
    enabled: yes
  register: apache_status_output
  notify: restart apache
