- name: Install php packages
  apt:
    name:
      - php8.1
      - php8.1-mysql
      - php8.1-curl
      - php8.1-gd
      - php8.1-mbstring
      - php8.1-xml
      - php8.1-zip
      - php8.1-intl
      - php8.1-ldap
      - libapache2-mod-php8.1
      - php8.1-fpm
      - php-intl
      - php-soap
    state: present
  ignore_errors: True

- name: Запустить сервис Apache2
  service:
    name: apache2
    state: started
    enabled: yes
  register: apache_status_output
  notify: restart apache
