- name: Install moodle39
  hosts: all                  # Целевые хосты (из инвентаря)
  become: yes                 # Выполнять задачи с повышенными привилегиями
  remote_user: root
  roles:
  - role: moodle39    # Подключение вашей роли
    vars:
