- name: Ensure wget is installed
  apt:
    name:
      - wget
      - bash
    state: present
    update_cache: yes

- name: Download and run BigBlueButton install script via wget
  shell: |
    wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v3.0.x-release/bbb-install.sh | bash -s -- -w -v {{ bbb_version }} s {{ bbb_hostname }} -e {{ bbb_email }} -g
  args:
    executable: /bin/bash

- name: Ensure firewall ports are open
  ufw:
    state: reset

- name: Get BigBlueButton API credentials
  shell: bbb-conf --secret
  register: bbb_conf_output
  changed_when: false

- name: Show BigBlueButton API URL and secret
  debug:
    msg: "{{ bbb_conf_output.stdout }}"
